# Generated by Django 5.2.6 on 2026-01-04 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_wage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('working_days_per_week', models.IntegerField(default=5)),
                ('working_hours_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('basic_percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('hra_percentage', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('standard_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('performance_bonus_percentage', models.DecimalField(decimal_places=2, default=8.33, max_digits=5)),
                ('leave_travel_allowance_percentage', models.DecimalField(decimal_places=2, default=8.33, max_digits=5)),
                ('food_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf_employee_percentage', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('pf_employer_percentage', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
